spring.application.name=alugafacil

spring.datasource.url=jdbc:postgresql://localhost:5432/alugafacil_db
spring.datasource.username=postgres
spring.datasource.password=Sda1945b
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

jwt.secret=alugafacil-chave-secreta-super-segura-2026-manoel
jwt.expiration=86400000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB